spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3307/promptoven-product
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product_service?authSource=admin
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: -1
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

logging:
  level:
    org.example.productreadservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.apache.kafka: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb: DEBUG

server:
  port: 8082